version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3100:3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=https://resume.sdet.school
      - PUBLIC_SERVER_URL=https://resume.sdet.school/api
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=AVUHZ3yyYWe734jEGGlg
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=2DsQv7YLv6ElezR4GElK
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=noreply@rxresu.me
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - STORAGE_BUCKET=
      - STORAGE_REGION=
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
      - PDF_DELETION_TIME=

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=https://resume.sdet.school
      - PUBLIC_SERVER_URL=https://resume.sdet.school/api
      - PUBLIC_GOOGLE_CLIENT_ID=


  proxy:
    build:
      dockerfile: Dockerfile
      context: "./proxy"
    restart: always
    ports:
      - "127.0.0.1:34343:34343"


volumes:
  pgdata:
