on:
  - push
  - pull_request

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      RELEASE_DIR: '/app/Resume'
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare directories
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            rm -rf ${{ env.RELEASE_DIR }}
            mkdir -p ${{ env.RELEASE_DIR }}

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ${{ env.RELEASE_DIR }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}