on:
  - push
  - pull_request

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      RELEASE_DIR: '/app/Resume'
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare directories
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |          
            mkdir -p ${{ env.RELEASE_DIR }}

      - name: Copy files to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ${{ env.RELEASE_DIR }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Docker Compose Up
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: false
          script: |
            docker-compose down
            cd ${{ env.RELEASE_DIR }}
            docker-compose up -d --build